analogs:
- !!python/tuple [176, 1]
- !!python/tuple [176, 2]
- !!python/tuple [176, 3]
- !!python/tuple [176, 4]
- !!python/tuple [176, 5]
- !!python/tuple [176, 6]
- !!python/tuple [176, 7]
- !!python/tuple [176, 8]
- !!python/tuple [176, 65]
- !!python/tuple [176, 66]
- !!python/tuple [176, 67]
- !!python/tuple [176, 68]
- !!python/tuple [176, 69]
- !!python/tuple [176, 70]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 73]
- !!python/tuple [176, 74]
- !!python/tuple [176, 75]
- !!python/tuple [176, 76]
- !!python/tuple [176, 77]
- !!python/tuple [176, 78]
- !!python/tuple [176, 79]
- !!python/tuple [176, 80]
- !!python/tuple [176, 81]
- !!python/tuple [176, 82]
- !!python/tuple [176, 83]
- !!python/tuple [176, 84]
- !!python/tuple [176, 85]
- !!python/tuple [176, 86]
- !!python/tuple [176, 87]
- !!python/tuple [176, 88]
- !!python/tuple [176, 9]
- !!python/tuple [176, 10]
- !!python/tuple [176, 11]
- !!python/tuple [176, 12]
- !!python/tuple [176, 13]
- !!python/tuple [176, 14]
- !!python/tuple [176, 15]
- !!python/tuple [176, 16]
- !!python/tuple [176, 17]
- !!python/tuple [176, 18]
- !!python/tuple [176, 19]
- !!python/tuple [176, 20]
- !!python/tuple [176, 21]
- !!python/tuple [176, 22]
- !!python/tuple [176, 23]
- !!python/tuple [176, 24]
- !!python/tuple [176, 25]
- !!python/tuple [176, 26]
- !!python/tuple [176, 27]
- !!python/tuple [176, 28]
- !!python/tuple [176, 29]
- !!python/tuple [176, 30]
- !!python/tuple [176, 31]
- !!python/tuple [176, 32]
device_name: BCF2000 MIDI 1
